/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAnnouncements: typeof import('./../components/admin/AdminAnnouncements.vue')['default']
    AdminFeedbacks: typeof import('./../components/admin/AdminFeedbacks.vue')['default']
    AdminMaintenance: typeof import('./../components/admin/AdminMaintenance.vue')['default']
    AdminReview: typeof import('./../components/admin/AdminReview.vue')['default']
    AdminUsers: typeof import('./../components/admin/AdminUsers.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ForumLineups: typeof import('./../components/forum/ForumLineups.vue')['default']
    ForumPosts: typeof import('./../components/forum/ForumPosts.vue')['default']
    ForumTournament: typeof import('./../components/forum/ForumTournament.vue')['default']
    ForumTutorials: typeof import('./../components/forum/ForumTutorials.vue')['default']
    HomeContent: typeof import('./../components/home/HomeContent.vue')['default']
    HomeSkeleton: typeof import('./../components/home/HomeSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
